### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by astridx**
Today I installed everything new. 
We do not need the changes in robofile.php any more. And the global installation is not needed (I am not sure if I was wrong when I added this suggestion here. But today it worked for me without the global installation).
I do not know where I can check the version number. But because of the file size I am sure that 2.25 (and not the current 2.26) is OK.

### CODE REVIEW

**Comment by 810** [comment]
Thanks, could you also change all readme's on the webdrivers on the bin dir.

**Comment by yvesh** [comment]
@astridx if we still are on 2.25 you can update them to 2.26 :) Thank you

**Comment by astridx** [comment]
@810 
:)  I was just amazed that my current firefox version is running again. I did not notice this at the weekend. The firefox Readme I will look at later - and you check if my changes are correct ?

@yvesh 
Where can I see exactly which driver is copied? Is this also done via Composer or are the Webdriver copied manually?

**Comment by yvesh** [comment]
@astridx This is done manually atm, as there is no official composer package (IIRC)

**Comment by astridx** [comment]
I close this PR because fo #34. Here are all the changes as well.

**Pull request closed without merging**
