### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by astridx**
New PR because of 
-Conflicts and 
-a failure in the version number and 
I was not able to change the PR: https://github.com/joomla-projects/selenium-server-standalone/pull/17

I changed the number of the version in the prior PR to "v2.53.1" because I find the line 
    "joomla-projects/selenium-server-standalone": "v2.53.1",
in composer.json in the folder /tests/codeception. 

Is the number v2.42 or v2.53.1 correct?

### CODE REVIEW

**Comment by astridx** [comment]
There are conflicts again. But I can 't see what conflicts and how I can solve them? How can I see what I have to do?

**Comment by 810** [comment]
i have send you a fix

**Comment by astridx** [comment]
@810 Thank you very much.
Where can I find the fix? Where did you sent it?

**Comment by wilsonge** [comment]
https://github.com/astridx/selenium-server-standalone/pull/1

**Comment by astridx** [comment]
@wilsonge Thank you :)

**Comment by wilsonge** [comment]
v2.53.1 is the right version btw :)

**Comment by astridx** [comment]
I changed the number of the version in the prior PR to "v2.53.1" because I find the line
"joomla-projects/selenium-server-standalone": "v2.53.1",
in composer.json in the folder /tests/codeception.

I would be happy if someone can explain me why the correct version number is v2.42 and why
the number in composer.json is v2.53.1 :)

**Comment by 810** [comment]
the version of the driver is 2.24.

This readme is for this driver only, So it should show the driver version, not the selenium version.

**Comment by yvesh** [comment]
@astridx The Chrome webdriver version is 2.24 (see 1)

The one of selenium-server-standalone is currently 2.53.1.1

Why? Because this the current stable version of Selenium is still 2.53.1 ;-) With Selenium 3 coming up. (see 2)
1. https://sites.google.com/a/chromium.org/chromedriver/downloads
2. http://www.seleniumhq.org/download/

**Comment by astridx** [comment]
@810 , @yvesh Thank you. Now I understand the versions.

**Pull request merged**
